protected/controllers/FaseController.php
<?php

class FaseController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }
    public function accessRules()
    {
        return array(
            /*array('allow', // allow authenticated user to perform 'create' and 'update' actions
                    'actions'=>array('update','index'),
                    'users'=>array('@'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                    'actions'=>array('create'),
                    'users'=>array('Admin','Trainer'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                    'actions'=>array('delete'),
                    'users'=>array('Admin'),
            ),*/
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('edit','index','delete','create','listBodyPart','listFase','exercise','AddExercise',
                    'NewAddExercise','dropsMethod','dropsBodyArea','dropsFamilyExercise','dropsExercise','SelectLaterality',
                    'CloneExercise','DeleteExercise','editFaseExercise','copyPhase','pastePhase','DropsRange','Pdf','NewEditFaseExercise',
                    'validateFirstExecution','SearchExercise'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }
	public function actionIndex($id=0)
	{
	    if (empty($id))
            throw new CHttpException(404,'The requested page does not exist.');
	    else
        {
            $user = Users::model()->findByPk($id);
            $param=Params::model()->findByAttributes(['codParam'=>'WORKOUTVIDEO']);

            $model=new UsersPhase();
            $model->idUser=$id;

            $model->setScenario('search');

            if(isset($_GET['UsersPhase']))
            {
                $model->attributes=$_GET['UsersPhase'];
            }
            $this->render('index',['user'=>$user,'model'=>$model,'param'=>$param]);
        }
	}
	public function actionCreate($id=0)
    {
        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $response=[];

            $model = new FaseCreateForm();
            if(isset($_POST['FaseCreateForm']))
            {
                $model->idUser=$id;
                $model->attributes=$_POST['FaseCreateForm'];
                if ($model->validate() && $model->save())
                {
                    $response['html']= '';
                    $response['id']=(integer)$model->id;
                    echo CJavaScript::jsonEncode($response);
                    Yii::app()->end();

                }
            }
            $response=[];
            $response['id']=0;
            $response['html']=$this->renderPartial('create',['model'=>$model],true,true);
            echo CJavaScript::jsonEncode($response);
            Yii::app()->end();
        }
    }
    public function actionEdit($id=0)
    {
        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $response=[];

            $model = new FaseCreateForm($id);
            if(isset($_POST['FaseCreateForm']))
            {
                $model->attributes=$_POST['FaseCreateForm'];
                if ($model->validate() && $model->save())
                {
                    $response['html']= '';
                    $response['id']=(integer)$model->id;
                    echo CJavaScript::jsonEncode($response);
                    Yii::app()->end();

                }
            }
            $response=[];
            $response['id']=0;
            $response['html']=$this->renderPartial('create',['model'=>$model],true,true);
            echo CJavaScript::jsonEncode($response);
            Yii::app()->end();
        }
    }
    public function actionDelete($id)
    {
        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $model = UsersPhase::model()->findByPk($id);
            if ($model === null)
                throw new CHttpException(404, 'The requested page does not exist.');

            /**
             * eliminar todos los registros relacionados de las siguientes tablas en el siguiente orden
             * 1. execution_exercise
             * 2. execution_exercise_calc
             * 3. execution
             * 4. user_phase_exercise
             * 5. user_phase
             */
            foreach ($model->executions as $execution) {
                foreach ($execution->executionExercises as $executionExercise) {
                    $executionExercise->delete();
                }
                foreach ($execution->executionExerciseCalcs as $executionExerciseCalc) {
                    $executionExerciseCalc->delete();
                }
                $execution->delete();
            }
            foreach ($model->userPhaseExercises as $userPhaseExercise) {
                $userPhaseExercise->delete();
            }
            $model->delete();
        }
    }
    public function actionListBodyPart()
    {

        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $model = new FaseCreateForm();
            $model->idBodyPart = $_POST['id'];

            echo CHtml::activeDropDownList($model,'idBodyPart',FaseCreateForm::bodyParts(),['empty'=>'Select ...','class'=>"form-control"]);
        }

    }
    public function actionListFase()
    {

        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $model = new FaseCreateForm();
            $model->idFase = $_POST['id'];

            echo CHtml::activeDropDownList($model,'idFase',FaseCreateForm::fases(),['empty'=>'Select ...','class'=>"form-control"]);
        }

    }
    /**
     * accion que permite agregarle a una userphase sus ejercicios
     * @param $id identificador de la userphase
     */
    public function actionExercise($id)
    {
        if (empty($id))
            throw new CHttpException(404,'The requested page does not exist.');
        else
        {
            $UsersPhase = UsersPhase::model()->findByPk($id);
            $model = new UserPhaseExercise('search');
            $model->idUserPhase = $id;

            if(isset($_GET['UserPhaseExercise']))
            {
                $model->attributes=$_GET['UserPhaseExercise'];
            }
            $this->render('exerciseView',['model'=>$model,'idUserPhase'=>$id,'UsersPhase'=>$UsersPhase]);
        }
    }
    public function actionAddExercise($id)
    {
        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $response=[];

            $model = new UserPhaseExerciseForm();
            if(isset($_POST['UserPhaseExerciseForm']))
            {
                try
                {
                    $model->idUserPhase=$id;
                    $model->attributes=$_POST['UserPhaseExerciseForm'];
                    //CVarDumper::dump($model->validate(),10,false);exit;
                    if ($model->validate() && $model->save())
                    {
                        $response['html']= '';
                        $response['id']=(integer)$model->id;
                        echo CJavaScript::jsonEncode($response);
                        Yii::app()->end();
                    }
                }
                catch (Exception $e)
                {
//                    CVarDumper::dump($e,10,false);exit;
                }

            }
            $response=[];
            $response['id']=0;
            $response['html']=$this->renderPartial('addExercise',['model'=>$model],true,true);
            echo CJavaScript::jsonEncode($response);
            Yii::app()->end();
        }

    }
    public function actionNewAddExercise($id)
    {
        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $response=[];

            $model = new NewUserPhaseExerciseForm();
            if(isset($_POST['NewUserPhaseExerciseForm']))
            {
                try
                {
                    $model->idUserPhase=$id;
                    $model->attributes=$_POST['NewUserPhaseExerciseForm'];

                    if(empty($model->idExercise))
                    {
                        $temp = Exercise::model()->findByPk($model->idExercise);
//                        $temp = new Exercise();
                        $model->idMethod = $temp->idMethod;
                        $model->idBodyArea = $temp->idBodyArea;
                        $model->idFamilyExercise = $temp->idFamilyExercise;
                        $model->idOrientation = $temp->idOrientation;
                        $model->idImplement = $temp->idImplement;
                        $model->idGrip = $temp->idGrip;
                        $model->idLaterality = $temp->idLaterality;
                    }

                    if ($model->validate() && $model->save())
                    {
                        $response['html']= '';
                        $response['id']=(integer)$model->id;
                        echo CJavaScript::jsonEncode($response);
                        Yii::app()->end();
                    }
                }
                catch (Exception $e)
                {
//                    CVarDumper::dump($e,10,false);exit;
                }

            }
            $response=[];
            $response['id']=0;
            $response['html']=$this->renderPartial('newAddExercise',['model'=>$model],true,true);
            echo CJavaScript::jsonEncode($response);
            Yii::app()->end();
        }

    }
    /**
     * funcion que retorna un json con las opciones de los dropdowns de intervalo de repeticion,
     * rest y rango de movimiento los cuales son dependientes del metodo
     * @param $id integer id del metodo seleccionado
     */
    public function actionDropsMethod()
    {

protected/views/prueba/_calculus.php
<?php
/**
 *
 * @var integer $j
 */
?>
<table class="table table-condensed table-responsive table-bordered">
    <tr>
        <td colspan="11"><h3 class="text-center" style="margin: 0px;padding: 0px">Calculos</h3></td>
    </tr>
    <tr>
        <th>Avg Weight</th>
        <th>Willks</th>
        <th>Avg Reps</th>
        <th>Rel Str</th>
        <th>Tot Sets</th>
        <th>Goal</th>
        <th>Tot Tonnage</th>
        <th>Tot Reps</th>
        <th>Avg Lift</th>
        <th>Max Lift</th>
        <th>%</th>
    </tr>
    <tr>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td><input type="text" name="goal" value="0" style="width: 30px;"></td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
    </tr>
</table>

protected/views/prueba/_exercices.php
<?php
/**
 *
 * @var PruebaController $this
 */
?>
<div class="exercice" id="exercice<?= $j?>">
    <div class="row">
        <h2>
            <div class="col-xs-12">
                <a class="title-link" href="#" data-toggle="exercice<?= $j?>"><span class="icon-change"><i class="fa fa-plus-square" aria-hidden="true"></i></span> Ejercicio <?=$j+1 ?></a>
                <!--<a href="https://www.youtube.com/watch?v=H9es_ERUuVg" target="_blank"><i class="fa fa-youtube-play" style="font-size: 20px"></i></a>-->
            </div>
        </h2>
    </div>
    <div class="slideContent" style="display: none;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;padding: 10px;">
        <?= CHtml::beginForm() ?>
        <div class="row">
            <div class="col-sm-12">
                <?php $this->renderPartial('_information',['j'=>$j]); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <?php $this->renderPartial('_calculus',['j'=>$j]); ?>
            </div>
        </div>
        <?php $this->renderPartial('_repetitions',['j'=>$j]); ?>
        <div class="text-right">
            <a class="btn btn-primary btn-save btn-lg btn-block" style="margin-top: 20px;" href="<?php echo Yii::app()->createAbsoluteUrl('prueba/update')?>">Save</a>
        </div>
        <?= CHtml::endForm()?>
        <?php $this->renderPartial('_historic',['j'=>$j]); ?>
    </div>
</div>

protected/views/prueba/_formExecution.php
<h1>Prueba de la grilla</h1>
<br>
<?= CHtml::beginForm() ?>
<div class="row">
    <div class="col-md-4 col-xs-4"><?= CHtml::label('fecha', 'fecha') ?></div><div class="col-md-2 col-xs-8"><?= CHtml::textField('fecha',date('Y-m-d'),['class'=>'form-control','style'=>'padding: 0px;'])  ?></div>
    <div class="hidden-xs hidden-sm col-md-6 text-right"><?= CHtml::link('Nueva Ejecucion','#',['class'=>'btn btn-primary']) ?></div>
</div>
<div class="row">
    <div class="col-md-4 col-xs-4"><?= CHtml::label('peso', 'peso') ?></div><div class="col-md-2 col-xs-8"><?= CHtml::textField('peso','0',['class'=>'form-control','style'=>'padding: 0px;'])  ?></div>
    <div class="col-md-4 col-xs-4"><?= CHtml::label('unidad Peso', 'unipeso') ?></div><div class="col-md-2 col-xs-8 text-center"><?= CHtml::radioButtonList('unipeso','Kg',['Kg'=>'Kg','Lbs'=>'Lbs'],['container'=>'','separator'=>''])  ?></div>
</div>
<div class="row hidden-md hidden-lg">
    <div class="col-xs-12"><?= CHtml::link('Nueva Ejecucion','#',['class'=>'btn btn-primary btn-block']) ?></div>
</div>
<?= CHtml::endForm()?>

protected/views/prueba/_historicCalcs.php
<?php
/**
 *
 */?>
<table class="table table-condensed table-responsive table-bordered">
    <tr>
        <td colspan="13"><h3 class="text-center" style="margin: 0px;padding: 0px">Calculos</h3></td>
    </tr>
    <tr>
        <th>Avg Weight</th>
        <th>Willks</th>
        <th>Avg Reps</th>
        <th>Rel Str</th>
        <th>Tot Sets</th>
        <th>Goal</th>
    </tr>
    <tr>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
    </tr>
    <tr>
        <th>Tot Tonnage</th>
        <th>Tot Reps</th>
        <th>Avg Lift</th>
        <th>Max Lift</th>
        <th>%</th>
        <th></th>
    </tr>
    <tr>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
        <td>00.0</td>
    </tr>
</table>

protected/views/prueba/_historicDetails.php
<?php
/**
 *
 */?>
<table class="table table-condensed table-responsive table-bordered">
    <tr>
        <td colspan="13"><h3 class="text-center" style="margin: 0px;padding: 0px">Reps</h3></td>
    </tr>
    <tr>
        <th class="text-center"></th>
        <th class="text-center">1</th>
        <th class="text-center">2</th>
        <th class="text-center">3</th>
        <th class="text-center">4</th>
        <th class="text-center">5</th>
        <th class="text-center">6</th>
        <th class="text-center">7</th>
        <th class="text-center">8</th>
        <th class="text-center">9</th>
        <th class="text-center">10</th>
        <th class="text-center">11</th>
        <th class="text-center">12</th>
    </tr>
    <tr>
        <th>W</th>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
    </tr>
    <tr>
        <th>R</th>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
    </tr>
    <tr>
        <th>MW</th>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
        <td>000.00</td>
    </tr>
</table>

protected/views/prueba/_information.php
<?php
/**
 *
 * @var integer $j
 */
?>
<table class="table table-condensed table-responsive table-bordered" style="margin-bottom: 10px">
        <tr>
            <td colspan="7"><h3 class="text-center" style="margin: 0px;padding: 0px">Exercise Information</h3></td>
        </tr>
        <tr>
            <th style="padding: 2px;text-align: center;vertical-align: middle">orden</th>
            <th style="padding: 2px;text-align: center;vertical-align: middle">rango movimiento</th>
            <th style="padding: 2px;text-align: center;vertical-align: middle">Intervalo De Repeticion</th>
            <th style="padding: 2px;text-align: center;vertical-align: middle">Numero De series</th>
            <th style="padding: 2px;text-align: center;vertical-align: middle">Tempo</th>
            <th style="padding: 2px;text-align: center;vertical-align: middle">Rest</th>
            <th style="padding: 2px;text-align: center;vertical-align: middle">Unidades</th>
        </tr>
        <tr>
            <td style="padding: 2px;text-align: center;vertical-align: middle">0</td>
            <td style="padding: 2px;text-align: center;vertical-align: middle">0</td>
            <td style="padding: 2px;text-align: center;vertical-align: middle">0</td>
            <td style="padding: 2px;text-align: center;vertical-align: middle">0</td>
            <td style="padding: 2px;text-align: center;vertical-align: middle">0</td>
            <td style="padding: 2px;text-align: center;vertical-align: middle">0</td>
            <td style="padding: 2px;text-align: center;vertical-align: middle"><?= CHtml::radioButtonList('unipeso'.$j,'Kg',['Kg'=>'Kg','Lbs'=>'Lbs'],['container'=>'','separator'=>''])  ?></td>
        </tr>
        <tr>
            <th style="padding: 2px;text-align: center;vertical-align: middle"><?= CHtml::label('Notas', 'notas') ?></th>
            <td colspan="6" style="padding: 2px;text-align: center;vertical-align: middle"><?= CHtml::textArea('notas','0',['class'=>'form-control','style'=>'padding: 0px;'])  ?></td>
        </tr>
</table>

protected/views/prueba/_repetitions.php
<?php
/**
 *
 * @var integer $j
 */
?>
<div class="row">
    <div class="col-md-1">
        <?= CHtml::label('W','campo01',['class'=>"col-md-1 col-xs-4 text-center col-sm-4"]) ?>
        <?= CHtml::label('R','campo02',['class'=>"col-md-1 col-xs-4 text-center col-sm-4"]) ?>
        <?= CHtml::label('MW','campo03',['class'=>"col-md-1 col-xs-4 text-center col-sm-4"]) ?>
    </div>
    <div class="col-md-11">
        <?php for($i=0;$i<12;$i++): ?>
            <div class="col-md-1 text-center" style="padding-left: 0px;padding-right: 0px">
                <?= CHtml::textField('campo01[]','1',['class'=>'col-md-12 col-xs-4 textfieldChange','style'=>'padding: 0px;background-color:transparent']) ?>
                <?= CHtml::textField('campo02[]','2',['class'=>'col-md-12 col-xs-4 textfieldChange','style'=>'padding: 0px;background-color:transparent']) ?>
                <?= CHtml::textField('campo03[]','3',['class'=>'col-md-12 col-xs-4 textfieldChange','style'=>'padding: 0px;background-color:transparent']) ?>
            </div>
        <?php endfor; ?>
    </div>
</div>

protected/views/prueba/exerciseView.php
<?php
/**
 *
 * @var FaseController $this
 * @var \UserPhaseExercise $model
 * @var \identificador $idUserPhase
 */

$baseUrl = Yii::app()->getBaseUrl(true);

$scriptDialog =<<<JS
$(document).on('click','#btnajaxCloneExercises',function(event) {
    event.preventDefault();
    var info=[];
    $.each($( ".checkboxValid:checked" ),function(index,value){
        info.push($(value).val());
    });
    $.ajax({
        url: $(this).attr('href'),
        data: {ids:info},
        type: 'POST',
        dataType:'json',
        success: function(response){
            if(response.valid>0)
                alert(response.message);
        },
        error: function(XMLHttpRequest, textStatus, errorThrown) {
            if(XMLHttpRequest.status == 403)
            {
                window.location.href='$baseUrl';
            }
        },
        complete: function() {
            $('#user-phase-exercise-grid').yiiGridView('update');
        }
     });
});
$(document).on('click','#btnajaxModalPhase,.xEditFaseExercise',function(event){     
    event.preventDefault();
     $.ajax({
            url: $(this).attr('href'),
            type: 'POST',
            dataType:'json',
            success: function(response){
                console.log(response);
                $("#ajaxModalPhase .modal-body").empty().html(response.html);
		        $("#ajaxModalPhase").modal();
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
                if(XMLHttpRequest.status == 403)
                {
                    window.location.href='$baseUrl';
                }
            }
        });
});
JS;

Yii::app()->clientScript->registerCssFile('https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css');
Yii::app()->clientScript->registerScriptFile('https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js', CClientScript::POS_END);

Yii::app()->clientScript->registerScript('scriptDialog',$scriptDialog,CClientScript::POS_READY);
?>
<h1>Exercises by Phase</h1>
<hr class="separator">
<div class="text-right">
    <?= CHtml::link('<i class="fa fa-clone"></i> Clone Exercises Selected',['fase/cloneExercise','id'=>$idUserPhase],['class'=>"btn btn-primary",'id'=>"btnajaxCloneExercises"]); ?>
    <?php if(Yii::app()->user->getState('userType')=='Practitioner1'):?>
        <?= CHtml::link('<i class="fa fa-plus-circle"></i> New Exercise',['fase/newAddExercise','id'=>$idUserPhase],['class'=>"btn btn-primary",'id'=>"btnajaxModalPhase"]); ?>
    <?php else: ?>
        <?= CHtml::link('<i class="fa fa-plus-circle"></i> New Exercise',['fase/addExercise','id'=>$idUserPhase],['class'=>"btn btn-primary",'id'=>"btnajaxModalPhase"]); ?>
    <?php endif; ?>

</div>
<br>
<div class="col-sm-12">
    <?php $this->widget('zii.widgets.grid.CGridView', array(
        'id'=>'user-phase-exercise-grid',
        'dataProvider'=>$model->search(),
        'filter'=>$model,
        'columns'=>array(
//            idExercise0
            [
                'header'=>'Order',
                'name'=>'order',
                'value'=>'!empty($data->order)?$data->order:""',
                'filter'=>CHtml::activeTextField($model,'order',['class'=>"form-control"])
            ],
            [
                'header'=>'Exercise Name',
                'name'=>'idExercise0.description',
                'value'=>'!empty($data->idExercise)?$data->idExercise0->description:""',
//                'value'=>'Yii::app()->dateFormatter->format("yyyy-MM-dd",$data->date)',
                'filter'=>CHtml::activeTextField($model,'exerciseDescription',['class'=>"form-control"])
            ],
            [
                'header'=>'Range',
//                'name'=>'idExercise0.idMethod0.description',
                'name'=>'idExercise0.idRangeMotion0.description',
                'value'=>'!empty($data->idRangeMotion0)?$data->idExercise0->idRangeMotion0->description:""',
//                'value'=>'Yii::app()->dateFormatter->format("yyyy-MM-dd",$data->date)',
                'filter'=>CHtml::activeTextField($model,'methodDescription',['class'=>"form-control"])
            ],
            [
                'header'=>'Sets',
                'name'=>'numberSeries',
                'value'=>'$data->numberSeries',
                'filter'=>CHtml::activeTextField($model,'numberSeries',['class'=>"form-control"])
            ],
            [
                'header'=>'Rep Int',
                'value'=>'$data->repeatInterval',
                'filter'=>CHtml::activeTextField($model,'repeatInterval',['class'=>"form-control"])
            ],
            [
                'header'=>'Tempo',
                'value'=>'$data->tempo',
                'filter'=>CHtml::activeTextField($model,'tempo',['class'=>"form-control"])
            ],
            [
                'header'=>'Rest(secs)',
                'value'=>'$data->rest',
                'filter'=>CHtml::activeTextField($model,'rest',['class'=>"form-control"])
            ],
            [
                'header'=>'TUT',
                'value'=>'$data->tut',
                'filter'=>CHtml::activeTextField($model,'tut',['class'=>"form-control"]),
                'footer'=>Tut::CalcTutTotalFooter($idUserPhase)
            ],
            /*[
                'header'=>'TUT Total',
                'value'=>'$data->tutTotal',
                'filter'=>CHtml::activeTextField($model,'tutTotal',['class'=>"form-control"]),
                'footer'=>Tut::CalcTutTotalFooter($idUserPhase)
            ],*/
            [
                'header'=> 'Clone',
                'headerTemplate'=>'<div style="white-space: nowrap">Clone {item}</div>',
                'class' => 'CCheckBoxColumn',
                'value' => '$data->id',
                'selectableRows' => 20,
                'checkBoxHtmlOptions'=>['class'=>'checkboxValid']
            ],
            array
            (
                'class'=>'CButtonColumn',
                'template'=>'<div style="white-space: nowrap">{xEditFaseExercise}{xDeleteFaseExercise}</div>',
                'header'=>"  Actions  ",
                'buttons'=>array(
                    'xEditFaseExercise'=>array(
                        'label'=>'<i class="fa fa-arrow-circle-up fa-2x hidden-lg hidden-md visible-sm-inline-block visible-xs-inline-block"></i>
								  <i class="fa fa-arrow-circle-up visible-lg-inline-block visible-md-inline-block hidden-sm hidden-xs"></i>&nbsp;&nbsp;',
                        'url'=>(Yii::app()->user->getState('userType')=='Practitioner1')?
                            'Yii::app()->createUrl("fase/newEditFaseExercise", array("id"=>$data->id))':
                            'Yii::app()->createUrl("fase/editFaseExercise", array("id"=>$data->id))',
                        'options'=>array('title'=>'Edit Exercise','class'=>'xEditFaseExercise')
                    ),
                    'xDeleteFaseExercise'=>array(
                        'label'=>'<i class="fa fa-minus-circle fa-2x hidden-lg hidden-md visible-sm-inline-block visible-xs-inline-block"></i>
								  <i class="fa fa-minus-circle visible-lg-inline-block visible-md-inline-block hidden-sm hidden-xs"></i>&nbsp;&nbsp;',
                        'url'=>'Yii::app()->createUrl("fase/DeleteExercise", array("id"=>$data->id))',
                        'options'=>array('title'=>'Delete Exercise'),
                        'click'=>"function() {
							if(!confirm('Are you sure you want to delete this item?')) return false;
							var th = this,afterDelete = function(){};
							jQuery('#user-phase-exercise-grid').yiiGridView('update', {
								type: 'POST',
								url: jQuery(this).attr('href'),
								success: function(data) {
									jQuery('#user-phase-exercise-grid').yiiGridView('update');
								afterDelete(th, true, data);
								},
								error: function(XHR) {
									return afterDelete(th, false, XHR);
								}
							});
							return false;
						}"
                    ),
                ),
            ),
        ),
    )); ?>
</div>
<div class="text-right">
    <?= CHtml::link('<i class="fa fa-arrow-circle-left"></i> Back',['fase/index','id'=>$userId],['class'=>"btn btn-primary"]); ?>
</div>
<div class="modal fade" id="ajaxModalPhase" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="preloader-alfa"></div>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Exercise in Phase</h2>
            </div>
            <div class="modal-body" style="text-align: justify;">
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                <a class="btn btn-primary" id="btnajaxModalNewFase"><i class="fa fa-plus-circle"></i> New Phase</a>
            </div>

        </div>
    </div>
</div>

protected/views/prueba/form1.php
<?php
/**
 *
 * @var PruebaController $this
 */